### ISSUE TITLE
[Feature] 학생 상세 페이지 구현

### ISSUE THREAD

**Issue by fepanbr** [GiSeok-Hong/wonderart-crm#50]
## Description
학생 상세페이지 기능 구현

## To-Do
- [x] 학생 상세페이지 연결
- [x] 학생 정보 수정 API 추가
- [x] 학생 정보 수정 기능 개발

## Deadline

- 23.08.31 ~ 23.09.01

## ETC
기타 사항이 있을 경우 작성하세요
