### ISSUE TITLE
[Feature] 학생 테이블에 '등록여부' 컬럼 추가, 관련 코드 수정

### ISSUE THREAD

**Issue by GiSeok-Hong** [GiSeok-Hong/wonderart-crm#58]
## Description
학생 테이블에 '등록여부' 컬럼을 추가하고 이와 관련된 코드들 수정

## To-Do
- [x] prisma schema 에 있는 Student 모델 수정
- [x] 입학원서 페이지에서 '등록여부' 코드 추가
- [x] 학원생 페이지에서 '등록여부' 코드 추가

## Deadline
작업 기한을 작성하세요
- 23.09.18 ~ 23.09.18

## ETC
기타 사항이 있을 경우 작성하세요
