### ISSUE TITLE
[Feature] 선생님 등록 팝업 개발

### ISSUE THREAD

**Issue by fepanbr** [GiSeok-Hong/wonderart-crm#64]
## Description
선생님을 등록할 수 있는 팝업을 개발합니다.

## To-Do
- [x] 등록 버튼 UI 개발
- [x] 팝업 UI 개발
- [x] 선생님 저장 API 생성

## Deadline
작업 기한을 작성하세요
- 23.09.22~23.09.23

## ETC
기타 사항이 있을 경우 작성하세요
