### ISSUE TITLE
[Feature] 사용자 요청 사항 - 학생 상세 페이지의 'select box' 부분 'radio button' 형식으로 변경 요청

### ISSUE THREAD

**Issue by GiSeok-Hong** [GiSeok-Hong/wonderart-crm#72]
**요청 사항**
학생 상세 페이지의 'select box' 부분 'radio button' 형식으로 변경 요청

## To-Do
- [x] 성별
- [x] 등록 여부
- [x] 원더아트 스튜디오를 선택한 이유
- [x] 학부모님이 가장 중요하다고 생각하는 미술활동
- [x] 학생이 가장 흥미있어 하는 미술활동

**스크린샷**
![스크린샷 2023-10-28 182722](https://github.com/GiSeok-Hong/wonderart-crm/assets/48499094/23e5f36b-bc21-4369-b766-fbbe2ddc1ee9)

* **아래 이미지와 같이 변경 요청**

![스크린샷 2023-10-28 183106](https://github.com/GiSeok-Hong/wonderart-crm/assets/48499094/b9cf284c-d8be-4c34-ae16-6f4d714369d1)
